id = "github-theme"
name = "GitHub"
version = "1.0.0"
api_version = 1
description = "GitHub Dark and GitHub Light."
authors = ["pairprogram"]
themes = ["themes/github-dark.json", "themes/github-light.json"]
